name: Cleanup Old Cloudflare Deployments

on:
  push:
    branches:
      - main # Đổi thành 'master' nếu nhánh chính của bạn là master

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup old deployments
        uses: batmany/cf-pages-clean-deployment@v1
        with:
          account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          project_name: 'zoey-in-borderland-cleanup' # Tên project Pages trên Cloudflare của bạn
          keep_last: 2 # Số lượng bản gần nhất muốn giữ lại
